### ISSUE TITLE
Подготовить скелет проекта панели управления для опенсорсной версии

### ISSUE THREAD

**Issue by demdxx** [sspserver/control#1]
> Задача прикреплена к репозиторию: https://github.com/sspserver/control

За снову берем "Header Layout"
https://ui.tailus.io/examples/application/

Добавить поддержку `graphql` на основе

```json
  "dependencies": {
    "graphql": "^16.8.1",
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^5.0.2",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1",
    "@graphql-codegen/typescript-react-apollo": "^3.3.7"
  },
```

В проекте будет только авторизация без регистрации новых пользователей

## Протокол:

`/api-protocol`

[Archive.zip](https://github.com/user-attachments/files/18245600/Archive.zip)

`codegen.yml`
`API_URL` - <https://api.rtb0.com>

```yaml
overwrite: true
schema: "${API_URL}"
documents:
  - "./api-protocol/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
config:
  withHooks: true
```

## Разделы основного меню

1. RTB - список источников рекламы
2. Applications - список сайтов/приложений где будет отображаться реклама
3. AdUnit - аналогично AdZone, AdSpot. Список мест для размещения рекламы. Никак не связаны с конкретным сайтом и может располагаться на нескольких. Служит для конфигурирования рекламы и правил распределения трафика
4. Settings - для всей системы. Будет разбито на несколько подразделов
